# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aef4d14149dd53ad7b5766bcfdb685fae80211a9770a1dc11c000996beba0492c12919988c158eab52e0e95bda748110733e1d425fc9081eef8495d2c464c786

test:
  secret_key_base: e151caf9eb959731572976307fc8b353a36d1c0c3c6e1628c0d7b5b3bb8338d97d7093bb81a95faf3b20a2c43282942410f374c2323e0db79baf2f7a40ac73ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
